/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.strategy.pattern.ducks;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
       
       Duck rubberDuck = new RubberDuck();
       Duck cityDuck = new CityDuck();

       System.out.println(rubberDuck.tryToQuack());
       System.out.println(cityDuck.tryToQuack());




    }
}
